<?
	$Page->Title = 'Main';
	include_once('includes/Header.inc.php');
?>

<p>
Site example, automatically generated by <a href='http://www.ajlopez.com/ajgenesis'>AjGenesis</a>,
using <a href="http://www.php.net">PHP</a> and <a href="http://www.mysql.com">MySql</a>.
</p>
<p>
Created by <a href="http://www.ajlopez.com">www.ajlopez.com</a>.
</p>


<?
	include_once('includes/Footer.inc.php');
?>
