'
' Automatically generated by AjGenesis
' http://www.ajlopez.com/ajgenesis
'

Module Module1

    Sub Main()
        System.Console.WriteLine("${Project.Message}")
    End Sub

End Module
