//
// Automatically generated by AjGenesis
// http://www.ajlopez.com/ajgenesis
//

using System;
using System.Collections.Generic;
using System.Text;

namespace ${Project.Name}Cs
{
    class Program
    {
        static void Main(string[] args)
        {
			Console.WriteLine("${Project.Message}");
        }
    }
}

