
//
// Automatically generated by AjGenesis
// http://www.ajlopez.com/ajgenesis
//

public class HelloWorld {

	public static void main(String[] args) {
		System.out.println("${Project.Message}");
	}

}
